---
TemplateFormatVersion: '2010-09-09'
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-97785bed
      InstanceType: t2.micro
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      StorageType: gp2
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: rootroot
  S3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wp-svarre-1128
